# DUSKWIRE // COZY VIOLET TWILIGHT
# Format: RRGGBBAA

night=1e195eff
indigo=3b298cff
periwinkle=555abbff
lavender=7f6ccfff
violet=9c4ec3ff
orchid=be74d1ff
pink=e893d1ff

amber=f4bd78ff
cream=fff0d1ff

text=eee8ffff
muted=bcb5e0ff

shadow=1a1338b8
