background #171331
foreground #eee8ff

background_opacity 0.80

selection_background #7f6ccb
selection_foreground #fff0d1

cursor #f4bd78
cursor_text_color #1e195e

active_border_color #e893d1
inactive_border_color #3b298c
