{ lib, ... }:

let
  colors = import ../../theme/colors.nix { inherit lib; };

  rgb = name:
    builtins.substring 0 6 colors.${name};

  configFiles = directory: prefix:
    builtins.listToAttrs (
      map
        (file:
          let
            relative = lib.removePrefix "${toString directory}/" (toString file);
          in
          {
            name = "${prefix}/${relative}";
            value.source = file;
          })
        (lib.filesystem.listFilesRecursive directory)
    );

  waybarColors = ''
    /* Generated by Duskwire from theme/colors.conf. */

    @define-color night #${rgb "night"};
    @define-color indigo #${rgb "indigo"};
    @define-color periwinkle #${rgb "periwinkle"};
    @define-color lavender #${rgb "lavender"};
    @define-color violet #${rgb "violet"};
    @define-color orchid #${rgb "orchid"};
    @define-color pink #${rgb "pink"};
    @define-color amber #${rgb "amber"};
    @define-color cream #${rgb "cream"};
    @define-color text #${rgb "text"};
    @define-color muted #${rgb "muted"};
    @define-color shadow #${rgb "shadow"};
  '';

  ewwColors = ''
    /* Generated by Duskwire from theme/colors.conf. */

    $night: #${rgb "night"};
    $indigo: #${rgb "indigo"};
    $periwinkle: #${rgb "periwinkle"};
    $lavender: #${rgb "lavender"};
    $violet: #${rgb "violet"};
    $orchid: #${rgb "orchid"};
    $pink: #${rgb "pink"};
    $amber: #${rgb "amber"};
    $cream: #${rgb "cream"};
    $text: #${rgb "text"};
    $muted: #${rgb "muted"};
    $shadow: #${rgb "shadow"};
  '';

  wofiColors = lib.concatMapStringsSep "\n" (name: "#${rgb name}") [
    "night"
    "indigo"
    "periwinkle"
    "lavender"
    "violet"
    "orchid"
    "pink"
    "amber"
    "cream"
    "text"
    "muted"
  ];
in
{
  xdg.configFile =
    configFiles ../../dotfiles/hypr "hypr"
    // configFiles ../../dotfiles/waybar "waybar"
    // configFiles ../../dotfiles/wofi "wofi"
    // configFiles ../../dotfiles/eww "eww"
    // {
      "VSCodium/User/settings.json".source =
        ../../dotfiles/VSCodium/User/settings.json;

      "duskwire/colors.conf".source = ../../theme/colors.conf;

      "waybar/colors.css".text = waybarColors;
      "eww/_colors.scss".text = ewwColors;
      "wofi/colors".text = "${wofiColors}\n";
    };
}
